# Generated by Django 4.2 on 2023-04-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company')),
                ('call_us', models.CharField(max_length=50)),
                ('email_us', models.CharField(max_length=50)),
                ('about', models.TextField(max_length=200)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('tw_link', models.URLField(blank=True, null=True)),
                ('inst_link', models.URLField(blank=True, null=True)),
                ('emails', models.TextField(max_length=200)),
                ('phones', models.TextField(max_length=200)),
                ('address', models.TextField(max_length=200)),
            ],
        ),
    ]
